### ISSUE TITLE
Merging with my repo?

### ISSUE THREAD

**Issue by ffMathy** [testpossessed/jsSubstitute#3]
Hi! 

Now that TypeScript 3.0 is out, we can express full strong typing all the way with the mocks, and also mock directly from interfaces using ES6 proxies!

See my own port of NSubstitute here: https://www.npmjs.com/package/@fluffy-spoon/substitute

Do you want to become a collaborator there and perhaps unify our projects?

**Comment by testpossessed** [comment]
Hi,

Sorry for some reason I never got the notification for this issue, back when you posted it.

I wrote this while working in JavaScript on a major AngularJS project and found limitations with Jasmine spies and did not like Sinon at all.  Since then I moved on to Angular and TypeScript and left this project behind.  I did start on something I was going to call tsSubstitute but never finished it.  With the much improved TestBed in Angular I found using anything other than Jasmine spies to be too messy.

Recently I created a VS Code extension and wanted to mock some parts of the VS Code API and ran into problems using Jasmine spies.  In the end the problem was more about trying to unit test something that doesn't exist unless you are running the VS Code host environment, which of course is what Integration Tests are for.  So the right thing to do is create and adapter for the VS Code API that I can mock in unit tests.

However the troubles led me back here and to thoughts of re-writing jsSubstitute with TypeScript and making it more compatible, but since you have already done that I don't need to.  I looked at typemoq, but I never liked Moq because of the need to use the .Object property instead of the actual Mock as we do with NSubstitute.

Anyway, enough waffle, I will take a closer look at your package and maybe talk to you over there.

Mike
